on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
        - name: Check Git repository
          uses: actions/checkout@v2
        - name: Install node
          uses: actions/setup-node@v1
          with:
            node-version: 16
        - name: Install dependencies
          run: npm install
        - name: Runs lint
          run: npm run lint
  mocha:
    runs-on: ubuntu-latest
    steps:
        - name: Check Git repository
          uses: actions/checkout@v2
        - name: Install node
          uses: actions/setup-node@v1
          with:
            node-version: 16
        - name: Run docker compose
          run: docker-compose up -d
        - name: Checks containers
          run: docker ps
        - name: Install dependencies
          run: npm install
        - name: Runs mocha tests
          run: npm run test